services:
  n8n:
    image: n8nio/n8n:2.17.8
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_SECURE_COOKIE: "false"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_RESTRICT_FILE_ACCESS_TO: /home/node/.n8n-files
      GENERIC_TIMEZONE: Asia/Saigon
      TZ: Asia/Saigon
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/workspace
      - ./runtime:/home/node/.n8n-files/runtime
    working_dir: /workspace
  runner:
    build:
      context: .
      dockerfile: runner/Dockerfile
    container_name: n8n-runner
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH: /usr/bin/chromium
      GOOGLE_SERVICE_ACCOUNT_FILE: /workspace/google-service-account.json
      HF_HOME: /models/huggingface
      HUGGINGFACE_HUB_CACHE: /models/huggingface/hub
      TZ: Asia/Saigon
    volumes:
      - ./:/workspace
      - ../project-iii-492308-fb6a394893e0.json:/workspace/google-service-account.json:ro
      - E:/n8n-ai-video-cache:/models
    working_dir: /workspace

volumes:
  n8n_data:
    external: true
    name: n8n_data
